language: node_js

node_js:
  - 'stable'
  - '8'

sudo: false

env:
NODE_ENV=test

matrix:
  fast_finish: true

branches:
  only:
  - master

#install:
#  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1